// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/kairos_node.proto

package kairospb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KairOSNode_ActivateDevice_FullMethodName   = "/kairos.v1.KairOSNode/ActivateDevice"
	KairOSNode_SendMessage_FullMethodName      = "/kairos.v1.KairOSNode/SendMessage"
	KairOSNode_SendFileChunk_FullMethodName    = "/kairos.v1.KairOSNode/SendFileChunk"
	KairOSNode_FetchQueue_FullMethodName       = "/kairos.v1.KairOSNode/FetchQueue"
	KairOSNode_GetContacts_FullMethodName      = "/kairos.v1.KairOSNode/GetContacts"
	KairOSNode_UpdateTrustScore_FullMethodName = "/kairos.v1.KairOSNode/UpdateTrustScore"
	KairOSNode_StoreAIMemory_FullMethodName    = "/kairos.v1.KairOSNode/StoreAIMemory"
	KairOSNode_RetrieveAIMemory_FullMethodName = "/kairos.v1.KairOSNode/RetrieveAIMemory"
)

// KairOSNodeClient is the client API for KairOSNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KairOSNodeClient interface {
	ActivateDevice(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error)
	SendMessage(ctx context.Context, in *MessagePacket, opts ...grpc.CallOption) (*SendResult, error)
	SendFileChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, TransferStatus], error)
	FetchQueue(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueuedItem], error)
	GetContacts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ContactList, error)
	UpdateTrustScore(ctx context.Context, in *TrustUpdate, opts ...grpc.CallOption) (*Empty, error)
	StoreAIMemory(ctx context.Context, in *MemoryEntry, opts ...grpc.CallOption) (*Empty, error)
	RetrieveAIMemory(ctx context.Context, in *MemoryQuery, opts ...grpc.CallOption) (*MemoryEntry, error)
}

type kairOSNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewKairOSNodeClient(cc grpc.ClientConnInterface) KairOSNodeClient {
	return &kairOSNodeClient{cc}
}

func (c *kairOSNodeClient) ActivateDevice(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateResponse)
	err := c.cc.Invoke(ctx, KairOSNode_ActivateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kairOSNodeClient) SendMessage(ctx context.Context, in *MessagePacket, opts ...grpc.CallOption) (*SendResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResult)
	err := c.cc.Invoke(ctx, KairOSNode_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kairOSNodeClient) SendFileChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, TransferStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KairOSNode_ServiceDesc.Streams[0], KairOSNode_SendFileChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, TransferStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KairOSNode_SendFileChunkClient = grpc.ClientStreamingClient[FileChunk, TransferStatus]

func (c *kairOSNodeClient) FetchQueue(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueuedItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KairOSNode_ServiceDesc.Streams[1], KairOSNode_FetchQueue_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchRequest, QueuedItem]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KairOSNode_FetchQueueClient = grpc.ServerStreamingClient[QueuedItem]

func (c *kairOSNodeClient) GetContacts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ContactList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContactList)
	err := c.cc.Invoke(ctx, KairOSNode_GetContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kairOSNodeClient) UpdateTrustScore(ctx context.Context, in *TrustUpdate, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, KairOSNode_UpdateTrustScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kairOSNodeClient) StoreAIMemory(ctx context.Context, in *MemoryEntry, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, KairOSNode_StoreAIMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kairOSNodeClient) RetrieveAIMemory(ctx context.Context, in *MemoryQuery, opts ...grpc.CallOption) (*MemoryEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryEntry)
	err := c.cc.Invoke(ctx, KairOSNode_RetrieveAIMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KairOSNodeServer is the server API for KairOSNode service.
// All implementations must embed UnimplementedKairOSNodeServer
// for forward compatibility.
type KairOSNodeServer interface {
	ActivateDevice(context.Context, *ActivateRequest) (*ActivateResponse, error)
	SendMessage(context.Context, *MessagePacket) (*SendResult, error)
	SendFileChunk(grpc.ClientStreamingServer[FileChunk, TransferStatus]) error
	FetchQueue(*FetchRequest, grpc.ServerStreamingServer[QueuedItem]) error
	GetContacts(context.Context, *Empty) (*ContactList, error)
	UpdateTrustScore(context.Context, *TrustUpdate) (*Empty, error)
	StoreAIMemory(context.Context, *MemoryEntry) (*Empty, error)
	RetrieveAIMemory(context.Context, *MemoryQuery) (*MemoryEntry, error)
	mustEmbedUnimplementedKairOSNodeServer()
}

// UnimplementedKairOSNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKairOSNodeServer struct{}

func (UnimplementedKairOSNodeServer) ActivateDevice(context.Context, *ActivateRequest) (*ActivateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateDevice not implemented")
}
func (UnimplementedKairOSNodeServer) SendMessage(context.Context, *MessagePacket) (*SendResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedKairOSNodeServer) SendFileChunk(grpc.ClientStreamingServer[FileChunk, TransferStatus]) error {
	return status.Error(codes.Unimplemented, "method SendFileChunk not implemented")
}
func (UnimplementedKairOSNodeServer) FetchQueue(*FetchRequest, grpc.ServerStreamingServer[QueuedItem]) error {
	return status.Error(codes.Unimplemented, "method FetchQueue not implemented")
}
func (UnimplementedKairOSNodeServer) GetContacts(context.Context, *Empty) (*ContactList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContacts not implemented")
}
func (UnimplementedKairOSNodeServer) UpdateTrustScore(context.Context, *TrustUpdate) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTrustScore not implemented")
}
func (UnimplementedKairOSNodeServer) StoreAIMemory(context.Context, *MemoryEntry) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreAIMemory not implemented")
}
func (UnimplementedKairOSNodeServer) RetrieveAIMemory(context.Context, *MemoryQuery) (*MemoryEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrieveAIMemory not implemented")
}
func (UnimplementedKairOSNodeServer) mustEmbedUnimplementedKairOSNodeServer() {}
func (UnimplementedKairOSNodeServer) testEmbeddedByValue()                    {}

// UnsafeKairOSNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KairOSNodeServer will
// result in compilation errors.
type UnsafeKairOSNodeServer interface {
	mustEmbedUnimplementedKairOSNodeServer()
}

func RegisterKairOSNodeServer(s grpc.ServiceRegistrar, srv KairOSNodeServer) {
	// If the following call panics, it indicates UnimplementedKairOSNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KairOSNode_ServiceDesc, srv)
}

func _KairOSNode_ActivateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairOSNodeServer).ActivateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KairOSNode_ActivateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairOSNodeServer).ActivateDevice(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KairOSNode_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagePacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairOSNodeServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KairOSNode_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairOSNodeServer).SendMessage(ctx, req.(*MessagePacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _KairOSNode_SendFileChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KairOSNodeServer).SendFileChunk(&grpc.GenericServerStream[FileChunk, TransferStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KairOSNode_SendFileChunkServer = grpc.ClientStreamingServer[FileChunk, TransferStatus]

func _KairOSNode_FetchQueue_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KairOSNodeServer).FetchQueue(m, &grpc.GenericServerStream[FetchRequest, QueuedItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KairOSNode_FetchQueueServer = grpc.ServerStreamingServer[QueuedItem]

func _KairOSNode_GetContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairOSNodeServer).GetContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KairOSNode_GetContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairOSNodeServer).GetContacts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KairOSNode_UpdateTrustScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrustUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairOSNodeServer).UpdateTrustScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KairOSNode_UpdateTrustScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairOSNodeServer).UpdateTrustScore(ctx, req.(*TrustUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _KairOSNode_StoreAIMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairOSNodeServer).StoreAIMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KairOSNode_StoreAIMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairOSNodeServer).StoreAIMemory(ctx, req.(*MemoryEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _KairOSNode_RetrieveAIMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairOSNodeServer).RetrieveAIMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KairOSNode_RetrieveAIMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairOSNodeServer).RetrieveAIMemory(ctx, req.(*MemoryQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// KairOSNode_ServiceDesc is the grpc.ServiceDesc for KairOSNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KairOSNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kairos.v1.KairOSNode",
	HandlerType: (*KairOSNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActivateDevice",
			Handler:    _KairOSNode_ActivateDevice_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _KairOSNode_SendMessage_Handler,
		},
		{
			MethodName: "GetContacts",
			Handler:    _KairOSNode_GetContacts_Handler,
		},
		{
			MethodName: "UpdateTrustScore",
			Handler:    _KairOSNode_UpdateTrustScore_Handler,
		},
		{
			MethodName: "StoreAIMemory",
			Handler:    _KairOSNode_StoreAIMemory_Handler,
		},
		{
			MethodName: "RetrieveAIMemory",
			Handler:    _KairOSNode_RetrieveAIMemory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendFileChunk",
			Handler:       _KairOSNode_SendFileChunk_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FetchQueue",
			Handler:       _KairOSNode_FetchQueue_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/kairos_node.proto",
}
