// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/kairos_node.proto

package kairospb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_kairos_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{0}
}

type ErrorStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorStatus) Reset() {
	*x = ErrorStatus{}
	mi := &file_proto_kairos_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorStatus) ProtoMessage() {}

func (x *ErrorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorStatus.ProtoReflect.Descriptor instead.
func (*ErrorStatus) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorStatus) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ActivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	KairNumber    string                 `protobuf:"bytes,2,opt,name=kair_number,json=kairNumber,proto3" json:"kair_number,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AdminCode     string                 `protobuf:"bytes,4,opt,name=admin_code,json=adminCode,proto3" json:"admin_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_proto_kairos_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{2}
}

func (x *ActivateRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ActivateRequest) GetKairNumber() string {
	if x != nil {
		return x.KairNumber
	}
	return ""
}

func (x *ActivateRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ActivateRequest) GetAdminCode() string {
	if x != nil {
		return x.AdminCode
	}
	return ""
}

type ActivateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Activated       bool                   `protobuf:"varint,1,opt,name=activated,proto3" json:"activated,omitempty"`
	ActivationState string                 `protobuf:"bytes,2,opt,name=activation_state,json=activationState,proto3" json:"activation_state,omitempty"`
	DeviceId        string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	KairNumber      string                 `protobuf:"bytes,4,opt,name=kair_number,json=kairNumber,proto3" json:"kair_number,omitempty"`
	Error           *ErrorStatus           `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActivateResponse) Reset() {
	*x = ActivateResponse{}
	mi := &file_proto_kairos_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateResponse) ProtoMessage() {}

func (x *ActivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateResponse.ProtoReflect.Descriptor instead.
func (*ActivateResponse) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{3}
}

func (x *ActivateResponse) GetActivated() bool {
	if x != nil {
		return x.Activated
	}
	return false
}

func (x *ActivateResponse) GetActivationState() string {
	if x != nil {
		return x.ActivationState
	}
	return ""
}

func (x *ActivateResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ActivateResponse) GetKairNumber() string {
	if x != nil {
		return x.KairNumber
	}
	return ""
}

func (x *ActivateResponse) GetError() *ErrorStatus {
	if x != nil {
		return x.Error
	}
	return nil
}

type MessagePacket struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	SenderKair       string                 `protobuf:"bytes,3,opt,name=sender_kair,json=senderKair,proto3" json:"sender_kair,omitempty"`
	ReceiverKair     string                 `protobuf:"bytes,4,opt,name=receiver_kair,json=receiverKair,proto3" json:"receiver_kair,omitempty"`
	Timestamp        int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EncryptedPayload []byte                 `protobuf:"bytes,6,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	NodeRoute        []string               `protobuf:"bytes,7,rep,name=node_route,json=nodeRoute,proto3" json:"node_route,omitempty"`
	HasAttachments   bool                   `protobuf:"varint,8,opt,name=has_attachments,json=hasAttachments,proto3" json:"has_attachments,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessagePacket) Reset() {
	*x = MessagePacket{}
	mi := &file_proto_kairos_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePacket) ProtoMessage() {}

func (x *MessagePacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePacket.ProtoReflect.Descriptor instead.
func (*MessagePacket) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{4}
}

func (x *MessagePacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessagePacket) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MessagePacket) GetSenderKair() string {
	if x != nil {
		return x.SenderKair
	}
	return ""
}

func (x *MessagePacket) GetReceiverKair() string {
	if x != nil {
		return x.ReceiverKair
	}
	return ""
}

func (x *MessagePacket) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessagePacket) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *MessagePacket) GetNodeRoute() []string {
	if x != nil {
		return x.NodeRoute
	}
	return nil
}

func (x *MessagePacket) GetHasAttachments() bool {
	if x != nil {
		return x.HasAttachments
	}
	return false
}

type SendResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	RetryCount    int32                  `protobuf:"varint,3,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	Error         *ErrorStatus           `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResult) Reset() {
	*x = SendResult{}
	mi := &file_proto_kairos_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResult) ProtoMessage() {}

func (x *SendResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResult.ProtoReflect.Descriptor instead.
func (*SendResult) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{5}
}

func (x *SendResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendResult) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *SendResult) GetError() *ErrorStatus {
	if x != nil {
		return x.Error
	}
	return nil
}

type FileChunk struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransferId       string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	SenderKair       string                 `protobuf:"bytes,2,opt,name=sender_kair,json=senderKair,proto3" json:"sender_kair,omitempty"`
	ReceiverKair     string                 `protobuf:"bytes,3,opt,name=receiver_kair,json=receiverKair,proto3" json:"receiver_kair,omitempty"`
	ChunkIndex       int32                  `protobuf:"varint,4,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks      int32                  `protobuf:"varint,5,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	EncryptedPayload []byte                 `protobuf:"bytes,6,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	Checksum         string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Timestamp        int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_kairos_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{6}
}

func (x *FileChunk) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileChunk) GetSenderKair() string {
	if x != nil {
		return x.SenderKair
	}
	return ""
}

func (x *FileChunk) GetReceiverKair() string {
	if x != nil {
		return x.ReceiverKair
	}
	return ""
}

func (x *FileChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *FileChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *FileChunk) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *FileChunk) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *FileChunk) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TransferStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransferId     string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ReceivedChunks int32                  `protobuf:"varint,3,opt,name=received_chunks,json=receivedChunks,proto3" json:"received_chunks,omitempty"`
	Error          *ErrorStatus           `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferStatus) Reset() {
	*x = TransferStatus{}
	mi := &file_proto_kairos_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStatus) ProtoMessage() {}

func (x *TransferStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStatus.ProtoReflect.Descriptor instead.
func (*TransferStatus) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{7}
}

func (x *TransferStatus) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferStatus) GetReceivedChunks() int32 {
	if x != nil {
		return x.ReceivedChunks
	}
	return 0
}

func (x *TransferStatus) GetError() *ErrorStatus {
	if x != nil {
		return x.Error
	}
	return nil
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverKair  string                 `protobuf:"bytes,1,opt,name=receiver_kair,json=receiverKair,proto3" json:"receiver_kair,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_proto_kairos_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{8}
}

func (x *FetchRequest) GetReceiverKair() string {
	if x != nil {
		return x.ReceiverKair
	}
	return ""
}

func (x *FetchRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type QueuedItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	EncryptedPayload []byte                 `protobuf:"bytes,3,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RetryCount       int32                  `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueuedItem) Reset() {
	*x = QueuedItem{}
	mi := &file_proto_kairos_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuedItem) ProtoMessage() {}

func (x *QueuedItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuedItem.ProtoReflect.Descriptor instead.
func (*QueuedItem) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{9}
}

func (x *QueuedItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueuedItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QueuedItem) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *QueuedItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *QueuedItem) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type Contact struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Knumber         string                 `protobuf:"bytes,1,opt,name=knumber,proto3" json:"knumber,omitempty"`
	DisplayName     string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	RealPhone       string                 `protobuf:"bytes,3,opt,name=real_phone,json=realPhone,proto3" json:"real_phone,omitempty"`
	Notes           string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	TrustStatus     string                 `protobuf:"bytes,5,opt,name=trust_status,json=trustStatus,proto3" json:"trust_status,omitempty"`
	LastInteraction int64                  `protobuf:"varint,6,opt,name=last_interaction,json=lastInteraction,proto3" json:"last_interaction,omitempty"`
	AvatarAscii     string                 `protobuf:"bytes,7,opt,name=avatar_ascii,json=avatarAscii,proto3" json:"avatar_ascii,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_proto_kairos_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{10}
}

func (x *Contact) GetKnumber() string {
	if x != nil {
		return x.Knumber
	}
	return ""
}

func (x *Contact) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Contact) GetRealPhone() string {
	if x != nil {
		return x.RealPhone
	}
	return ""
}

func (x *Contact) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Contact) GetTrustStatus() string {
	if x != nil {
		return x.TrustStatus
	}
	return ""
}

func (x *Contact) GetLastInteraction() int64 {
	if x != nil {
		return x.LastInteraction
	}
	return 0
}

func (x *Contact) GetAvatarAscii() string {
	if x != nil {
		return x.AvatarAscii
	}
	return ""
}

type ContactList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      []*Contact             `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	Error         *ErrorStatus           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactList) Reset() {
	*x = ContactList{}
	mi := &file_proto_kairos_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactList) ProtoMessage() {}

func (x *ContactList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactList.ProtoReflect.Descriptor instead.
func (*ContactList) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{11}
}

func (x *ContactList) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *ContactList) GetError() *ErrorStatus {
	if x != nil {
		return x.Error
	}
	return nil
}

type TrustUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KairNumber    string                 `protobuf:"bytes,1,opt,name=kair_number,json=kairNumber,proto3" json:"kair_number,omitempty"`
	Delta         float64                `protobuf:"fixed64,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustUpdate) Reset() {
	*x = TrustUpdate{}
	mi := &file_proto_kairos_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustUpdate) ProtoMessage() {}

func (x *TrustUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustUpdate.ProtoReflect.Descriptor instead.
func (*TrustUpdate) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{12}
}

func (x *TrustUpdate) GetKairNumber() string {
	if x != nil {
		return x.KairNumber
	}
	return ""
}

func (x *TrustUpdate) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *TrustUpdate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MemoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemoryType    string                 `protobuf:"bytes,2,opt,name=memory_type,json=memoryType,proto3" json:"memory_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Importance    float64                `protobuf:"fixed64,5,opt,name=importance,proto3" json:"importance,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryEntry) Reset() {
	*x = MemoryEntry{}
	mi := &file_proto_kairos_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryEntry) ProtoMessage() {}

func (x *MemoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryEntry.ProtoReflect.Descriptor instead.
func (*MemoryEntry) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{13}
}

func (x *MemoryEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryEntry) GetMemoryType() string {
	if x != nil {
		return x.MemoryType
	}
	return ""
}

func (x *MemoryEntry) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *MemoryEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryEntry) GetImportance() float64 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *MemoryEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type MemoryQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryQuery) Reset() {
	*x = MemoryQuery{}
	mi := &file_proto_kairos_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryQuery) ProtoMessage() {}

func (x *MemoryQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kairos_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryQuery.ProtoReflect.Descriptor instead.
func (*MemoryQuery) Descriptor() ([]byte, []int) {
	return file_proto_kairos_node_proto_rawDescGZIP(), []int{14}
}

func (x *MemoryQuery) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_proto_kairos_node_proto protoreflect.FileDescriptor

const file_proto_kairos_node_proto_rawDesc = "" +
	"\n" +
	"\x17proto/kairos_node.proto\x12\tkairos.v1\"\a\n" +
	"\x05Empty\";\n" +
	"\vErrorStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8d\x01\n" +
	"\x0fActivateRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vkair_number\x18\x02 \x01(\tR\n" +
	"kairNumber\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12\x1d\n" +
	"\n" +
	"admin_code\x18\x04 \x01(\tR\tadminCode\"\xc7\x01\n" +
	"\x10ActivateResponse\x12\x1c\n" +
	"\tactivated\x18\x01 \x01(\bR\tactivated\x12)\n" +
	"\x10activation_state\x18\x02 \x01(\tR\x0factivationState\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vkair_number\x18\x04 \x01(\tR\n" +
	"kairNumber\x12,\n" +
	"\x05error\x18\x05 \x01(\v2\x16.kairos.v1.ErrorStatusR\x05error\"\x8c\x02\n" +
	"\rMessagePacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vsender_kair\x18\x03 \x01(\tR\n" +
	"senderKair\x12#\n" +
	"\rreceiver_kair\x18\x04 \x01(\tR\freceiverKair\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12+\n" +
	"\x11encrypted_payload\x18\x06 \x01(\fR\x10encryptedPayload\x12\x1d\n" +
	"\n" +
	"node_route\x18\a \x03(\tR\tnodeRoute\x12'\n" +
	"\x0fhas_attachments\x18\b \x01(\bR\x0ehasAttachments\"\x83\x01\n" +
	"\n" +
	"SendResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vretry_count\x18\x03 \x01(\x05R\n" +
	"retryCount\x12,\n" +
	"\x05error\x18\x04 \x01(\v2\x16.kairos.v1.ErrorStatusR\x05error\"\x9d\x02\n" +
	"\tFileChunk\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1f\n" +
	"\vsender_kair\x18\x02 \x01(\tR\n" +
	"senderKair\x12#\n" +
	"\rreceiver_kair\x18\x03 \x01(\tR\freceiverKair\x12\x1f\n" +
	"\vchunk_index\x18\x04 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x05 \x01(\x05R\vtotalChunks\x12+\n" +
	"\x11encrypted_payload\x18\x06 \x01(\fR\x10encryptedPayload\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"\xa0\x01\n" +
	"\x0eTransferStatus\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0freceived_chunks\x18\x03 \x01(\x05R\x0ereceivedChunks\x12,\n" +
	"\x05error\x18\x04 \x01(\v2\x16.kairos.v1.ErrorStatusR\x05error\"P\n" +
	"\fFetchRequest\x12#\n" +
	"\rreceiver_kair\x18\x01 \x01(\tR\freceiverKair\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\x9c\x01\n" +
	"\n" +
	"QueuedItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12+\n" +
	"\x11encrypted_payload\x18\x03 \x01(\fR\x10encryptedPayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\x05R\n" +
	"retryCount\"\xec\x01\n" +
	"\aContact\x12\x18\n" +
	"\aknumber\x18\x01 \x01(\tR\aknumber\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"real_phone\x18\x03 \x01(\tR\trealPhone\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\x12!\n" +
	"\ftrust_status\x18\x05 \x01(\tR\vtrustStatus\x12)\n" +
	"\x10last_interaction\x18\x06 \x01(\x03R\x0flastInteraction\x12!\n" +
	"\favatar_ascii\x18\a \x01(\tR\vavatarAscii\"k\n" +
	"\vContactList\x12.\n" +
	"\bcontacts\x18\x01 \x03(\v2\x12.kairos.v1.ContactR\bcontacts\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x16.kairos.v1.ErrorStatusR\x05error\"\\\n" +
	"\vTrustUpdate\x12\x1f\n" +
	"\vkair_number\x18\x01 \x01(\tR\n" +
	"kairNumber\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x01R\x05delta\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xb4\x01\n" +
	"\vMemoryEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmemory_type\x18\x02 \x01(\tR\n" +
	"memoryType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"importance\x18\x05 \x01(\x01R\n" +
	"importance\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\x1f\n" +
	"\vMemoryQuery\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key2\x91\x04\n" +
	"\n" +
	"KairOSNode\x12I\n" +
	"\x0eActivateDevice\x12\x1a.kairos.v1.ActivateRequest\x1a\x1b.kairos.v1.ActivateResponse\x12>\n" +
	"\vSendMessage\x12\x18.kairos.v1.MessagePacket\x1a\x15.kairos.v1.SendResult\x12B\n" +
	"\rSendFileChunk\x12\x14.kairos.v1.FileChunk\x1a\x19.kairos.v1.TransferStatus(\x01\x12>\n" +
	"\n" +
	"FetchQueue\x12\x17.kairos.v1.FetchRequest\x1a\x15.kairos.v1.QueuedItem0\x01\x127\n" +
	"\vGetContacts\x12\x10.kairos.v1.Empty\x1a\x16.kairos.v1.ContactList\x12<\n" +
	"\x10UpdateTrustScore\x12\x16.kairos.v1.TrustUpdate\x1a\x10.kairos.v1.Empty\x129\n" +
	"\rStoreAIMemory\x12\x16.kairos.v1.MemoryEntry\x1a\x10.kairos.v1.Empty\x12B\n" +
	"\x10RetrieveAIMemory\x12\x16.kairos.v1.MemoryQuery\x1a\x16.kairos.v1.MemoryEntryB;Z9github.com/kairos-project/kairos/proto/kairos/v1;kairospbb\x06proto3"

var (
	file_proto_kairos_node_proto_rawDescOnce sync.Once
	file_proto_kairos_node_proto_rawDescData []byte
)

func file_proto_kairos_node_proto_rawDescGZIP() []byte {
	file_proto_kairos_node_proto_rawDescOnce.Do(func() {
		file_proto_kairos_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kairos_node_proto_rawDesc), len(file_proto_kairos_node_proto_rawDesc)))
	})
	return file_proto_kairos_node_proto_rawDescData
}

var file_proto_kairos_node_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_kairos_node_proto_goTypes = []any{
	(*Empty)(nil),            // 0: kairos.v1.Empty
	(*ErrorStatus)(nil),      // 1: kairos.v1.ErrorStatus
	(*ActivateRequest)(nil),  // 2: kairos.v1.ActivateRequest
	(*ActivateResponse)(nil), // 3: kairos.v1.ActivateResponse
	(*MessagePacket)(nil),    // 4: kairos.v1.MessagePacket
	(*SendResult)(nil),       // 5: kairos.v1.SendResult
	(*FileChunk)(nil),        // 6: kairos.v1.FileChunk
	(*TransferStatus)(nil),   // 7: kairos.v1.TransferStatus
	(*FetchRequest)(nil),     // 8: kairos.v1.FetchRequest
	(*QueuedItem)(nil),       // 9: kairos.v1.QueuedItem
	(*Contact)(nil),          // 10: kairos.v1.Contact
	(*ContactList)(nil),      // 11: kairos.v1.ContactList
	(*TrustUpdate)(nil),      // 12: kairos.v1.TrustUpdate
	(*MemoryEntry)(nil),      // 13: kairos.v1.MemoryEntry
	(*MemoryQuery)(nil),      // 14: kairos.v1.MemoryQuery
}
var file_proto_kairos_node_proto_depIdxs = []int32{
	1,  // 0: kairos.v1.ActivateResponse.error:type_name -> kairos.v1.ErrorStatus
	1,  // 1: kairos.v1.SendResult.error:type_name -> kairos.v1.ErrorStatus
	1,  // 2: kairos.v1.TransferStatus.error:type_name -> kairos.v1.ErrorStatus
	10, // 3: kairos.v1.ContactList.contacts:type_name -> kairos.v1.Contact
	1,  // 4: kairos.v1.ContactList.error:type_name -> kairos.v1.ErrorStatus
	2,  // 5: kairos.v1.KairOSNode.ActivateDevice:input_type -> kairos.v1.ActivateRequest
	4,  // 6: kairos.v1.KairOSNode.SendMessage:input_type -> kairos.v1.MessagePacket
	6,  // 7: kairos.v1.KairOSNode.SendFileChunk:input_type -> kairos.v1.FileChunk
	8,  // 8: kairos.v1.KairOSNode.FetchQueue:input_type -> kairos.v1.FetchRequest
	0,  // 9: kairos.v1.KairOSNode.GetContacts:input_type -> kairos.v1.Empty
	12, // 10: kairos.v1.KairOSNode.UpdateTrustScore:input_type -> kairos.v1.TrustUpdate
	13, // 11: kairos.v1.KairOSNode.StoreAIMemory:input_type -> kairos.v1.MemoryEntry
	14, // 12: kairos.v1.KairOSNode.RetrieveAIMemory:input_type -> kairos.v1.MemoryQuery
	3,  // 13: kairos.v1.KairOSNode.ActivateDevice:output_type -> kairos.v1.ActivateResponse
	5,  // 14: kairos.v1.KairOSNode.SendMessage:output_type -> kairos.v1.SendResult
	7,  // 15: kairos.v1.KairOSNode.SendFileChunk:output_type -> kairos.v1.TransferStatus
	9,  // 16: kairos.v1.KairOSNode.FetchQueue:output_type -> kairos.v1.QueuedItem
	11, // 17: kairos.v1.KairOSNode.GetContacts:output_type -> kairos.v1.ContactList
	0,  // 18: kairos.v1.KairOSNode.UpdateTrustScore:output_type -> kairos.v1.Empty
	0,  // 19: kairos.v1.KairOSNode.StoreAIMemory:output_type -> kairos.v1.Empty
	13, // 20: kairos.v1.KairOSNode.RetrieveAIMemory:output_type -> kairos.v1.MemoryEntry
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_kairos_node_proto_init() }
func file_proto_kairos_node_proto_init() {
	if File_proto_kairos_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kairos_node_proto_rawDesc), len(file_proto_kairos_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kairos_node_proto_goTypes,
		DependencyIndexes: file_proto_kairos_node_proto_depIdxs,
		MessageInfos:      file_proto_kairos_node_proto_msgTypes,
	}.Build()
	File_proto_kairos_node_proto = out.File
	file_proto_kairos_node_proto_goTypes = nil
	file_proto_kairos_node_proto_depIdxs = nil
}
